
//userContext
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const REGISTER_SUCESS = 'REGISTER_SUCESS'
export const GET_USER = 'GET_USER'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
export const SIGN_OFF = 'SIGN_OFF'
export const GET_ROLE = 'GET_ROLE'
export const ADD_PRUDUCT_SUCCESSFUL = 'ADD_PRUDUCT_SUCCESSFUL'
